### ISSUE TITLE
Python3 ldap module is currently not working with the code

### ISSUE THREAD

**Issue by cal-id** [cal-id/StatusJsonDatasource#11]
```
(python3) tan49775@vm216:~/StatusJsonDatasource (master)$ python updateStorageUsage_MoreDetails.py
Traceback (most recent call last):
  File "updateStorageUsage_MoreDetails.py", line 31, in <module>
    ldapObject = ldap.open(LDAP_HOST, 2170)  # open the ldap server
AttributeError: 'module' object has no attribute 'open'

```

**Comment by cal-id** [comment]
# Also on python2.7

(python2.7) tan49775@vm216:~/StatusJsonDatasource (master)$ python updateStorageUsage_MoreDetails.py
Traceback (most recent call last):
  File "updateStorageUsage_MoreDetails.py", line 31, in <module>
    ldapObject = ldap.open(LDAP_HOST, 2170)  # open the ldap server
AttributeError: 'module' object has no attribute 'open'
